spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configuration-server
      server:
        git:
          uri: git clone ssh://git@lepi.pl:443/git/spring-cloud-test-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888
